### ISSUE TITLE
Keep Native Multi-Folder Grouping for Libraries

### ISSUE THREAD

**Issue by megamorphg** [LesFerch/WinSetView#101]
Steps to Reproduce:
1. Create a library with two different folders
2. Configure WinSetView to show details and no groups by default in all folders

Expected Result:
Have option to have Libraries still grouped by the directory location since they contain multiple folders

Actual Result:
Library location's files are listed in all in one folder rather than separate folders

Attempted solution:
Configure WinSetView to show details and group by Folder:
![image](https://github.com/LesFerch/WinSetView/assets/1782353/2e2e5a5c-75a0-4cb0-97a1-161c5ee577a5)

But this causes some negative side effects:
- *all* folders/libraries have a useless group, even if it doesn't have any folders.
- Libraries with multiple folders have groups but they are not sorted the same way that the Library's properties settings folders are listed (they are sorted alphabetically instead).

The native way that Windows works with multi-folder Libraries is better so it would be great to have some option to allow to keep that.

**Comment by LesFerch** [comment]
Coincidentally, I just posted about that on Reddit:

https://www.reddit.com/r/WindowsHelp/comments/1b968sl/comment/kvtib4c/?utm_source=share&utm_medium=web2x&context=3

As noted in my Reddit post, there are two options that work well:

Option 1: Uncheck Inherit for any library that you want to have a view that differs from your Global setting and set the view for that library to be grouped by Folder Path (File Location in Windows 11). Don't change your Global setting to grouped.

Option 2: Uncheck the library folder type so that it retains the Windows default view (which is actually an Arrange by view), like this:

![image](https://github.com/LesFerch/WinSetView/assets/79026235/fa2cbf62-a07a-48ca-87af-f3403165532d)

Option 2 actually answers the request to "Keep Native Multi-Folder Library Grouping".

Also, as noted in the Reddit post, in Explorer, you can switch back to the default Arrange by Folder view in a library by right-clicking and selecting Arrange by **Clear changes**.

**Comment by LesFerch** [comment]
I'll keep this open with a title change to **Add "Arrange by" settings for libraries** and label it as an enhancement.

**Comment by LesFerch** [comment]
I did some research on this today and determined that "Arrange by" is not the answer. That's essentially an entire saved view, including column headings, sort and grouping, etc.

What we're really looking for is the property **ItemSearchLocation** and it turns out it was there all along. It's English name is "**By location**". Just group your libraries on that property and you will get the default grouping for libraries with your preferred columns, etc.

![image](https://github.com/LesFerch/WinSetView/assets/79026235/3be869c8-49c9-4e1a-81ea-2eeb624f8f64)

**Comment by LesFerch** [comment]
I will update the documentation with a note about this.

**Comment by LesFerch** [comment]
Excellent! And nice to hear that the copy-paste feature came in handy. 🙂

**Comment by LesFerch** [comment]
Version 2.94 sets the "By Location" grouping for Libraries automatically. The Options menu provides an override.
