### ISSUE TITLE
[Feature Request]: add one checkbox in options for "show hidden folders"

### ISSUE THREAD

**Issue by DebugBill** [LesFerch/WinSetView#111]
The tool is already awesome, but I lack a very small feature that I hope is easy to add: the "show hidden folders" checkbox that is available next to the "hide known extensions"  in the standard options in explorer;

I am more a Linux guy and not able to to the coding myself for Windows, so sorry I can't contribute the patch as I would otherwise try to.

**Comment by LesFerch** [comment]
It's a relatively easy addition, but I've been trying to avoid duplicating too much of what's already built in as a single click. The first two options in the WinSetView Options menu, "Show file extensions" and "Enable compact view in Windows 11", are arguably unnecessary because they fall into that category, but I feel strongly that file extensions should never being hidden in Windows and the default non-compact view in Windows 11 on non-tablet devices seemed silly.

Personally, I like to keep the hidden folders hidden (except **AppData**) as I rarely need to access them and, instead, I have a [right-click item](https://lesferch.github.io/RightClickTools/) that will let me enable/disable the display of both hidden and system items very quickly.

I'll consider this request for a future update, but I have to clarify if you only need to see hidden items or also see system items (protected operating system files):

![image](https://github.com/LesFerch/WinSetView/assets/79026235/0d131bca-e7c8-41e0-a802-95315ae57f3f)

Also note that if you only need AppData unhidden, there's already a checkbox for that:

![image](https://github.com/LesFerch/WinSetView/assets/79026235/568569d5-9258-4571-b983-9d5905563cd9)

**Comment by LesFerch** [comment]
In the meantime, extract the attached reg file to WinSetView's AppData subfolder. Uncomment the last line if you also want to see items that have the System attribute set.
[WinSetViewCustom.zip](https://github.com/LesFerch/WinSetView/files/15213390/WinSetViewCustom.zip)

**Comment by DebugBill** [comment]
Hi,

Thanks for your answer.

I manage the hosting service for our company, a software editor, and I like to have all our servers configured the same way. I also like when I connect to a customer's server to quickly configure it with all my usual tools and confs. My goal is to use the script version of you tool to enforce common settings to all servers and users, including file type associations, and/or to deploy my conf on any account I am given on a machine. I fully understand your concern about not duplicating existing controls, but my goal is to automatize as much as I can the enforcement of common settings. I would only use the GUI version once, and then apply the result everywhere.
Our app hides folders from users..... but maintenance agents need to access them, hence the need to show hidden folders but not system files.

**Comment by LesFerch** [comment]
Sounds good. The attached reg file in my previous reply should do the trick.

**Comment by DebugBill** [comment]
Thanks, I'll test it tomorrow at work.

**Comment by DebugBill** [comment]
Hi,
It works fine, so now I can use your tool and the additional reg conjointly to reach my goal
Thanks

**Comment by LesFerch** [comment]
Great! I'm not sure I was clear, but if you put the reg file in WinSetView's AppData subfolder, it will be applied automatically.

**Comment by LesFerch** [comment]
This option is now in the Options menu in version 2.97.
