### ISSUE TITLE
Narrow file spacing after backup restore (win11)

### ISSUE THREAD

**Issue by AngelDavil88** [LesFerch/WinSetView#119]
I used the program to delete the groups and set them to "none" but I noticed that the spacing between files is narrow while in wimdows 11 it was not like that. I then restored it to the original state again via the program but the spacing remained narrow and I don't like it. Is it possible to have an original Windows 11 Pro INI file in order to restore everything to its original state?
![IMG_20240801_013520](https://github.com/user-attachments/assets/2c15a855-ca4d-4dec-aabf-b5a007ba83d2)

The one in the photo is the large space between the Windows 11 files I had before using the program!

**Comment by LesFerch** [comment]
As per the [Quick Start Guide](https://lesferch.github.io/WinSetView/#how-to-use), you're expected to check the items in the **Options** menu and ensure that they're set to your liking:

[Step 5: Check and Set Your Desired Options](https://lesferch.github.io/WinSetView/#step-5-check-and-set-your-desired-options)

Windows 11 Compact View is enabled by default because that's what most power users seem to want, but you can just uncheck it like this:

![image](https://github.com/user-attachments/assets/58742145-9453-48a8-ae15-e7094074bfee)

Also note that the classic context menu is enabled by default. Again, just uncheck it if you want the Windows 11 context menu.

As for the **Restore** feature, it only restores the folder views. Options have to be set as you like in the Options menu.
