### ISSUE TITLE
Issue with applying template to downloads folder Template

### ISSUE THREAD

**Issue by Raynbda** [LesFerch/WinSetView#122]
Whenever i customize the downloads folder template it either gets the global or general items view or it applies what i set in the downloads folder template to folders with a general items folder template. I think this happens because the downloads folder is not in it's default folder since i moved it to c drive
I want to either be able to make it work properly or at least make winsetview reset it to the general items folder template every time i submit a change to any other template. Unchecking the downloads box in winsetview does not work.

**Comment by LesFerch** [comment]
Your moved Downloads folder is probably not folder type Downloads. It's type may be General or may follows it's contents.

I'll run some tests with a relocated Downloads folder when I'm back at my PC.

Is that folder located on a disk of type "local disk" or "USB drive" or "Network"? Is it formatted NTFS? Are you using the Windows 10 or Windows 11 Explorer?

**Comment by Raynbda** [comment]
When i open the properties i see that it’s optimized for general item but that would also happen even if i didn’t move the folder, no? I relocated the downloads folder from the default location in user folder under c: drive (SSD) where i installed windows to the d: drive (HDD) it’s not a usb drive or network. I am using file explorer windows 11 23H2. What is formatted NTFS?

**Comment by LesFerch** [comment]
Explorer always says the Download folder is type "General items" but that's a bug. The folder type is actually "Downloads". It shouldn't even show the Customize tab at all. For example, if you right click the Contacts folder (that's inside your user folder) it will not have a Customize button because it's a special folder type. The Downloads folder used to be just another folder of type "General items". When Microsoft changed its type to "Downloads" they forgot a few things like ensuring that the Customize tab is not shown. You should see that attempting to change the Downloads folder to a different folder type, such as Pictures, does not work.

I just did a test where I used the folder's Location tab to change my Downloads folder location to F:\Downloads. That folder picked up the view I set in WinSetView for Downloads, so I know it's type Downloads.

What procedure did you use to relocate your Downloads folder?

BTW, a disk can be formatted in different ways, such as NTFS, FAT32, ExFAT, etc. Chances are, your D: drive is formatted NTFS and is type "local disk". Verify that by opening the properties for the drive. You should see something like this:
![image](https://github.com/user-attachments/assets/796c9baf-4259-4f5f-89b5-6bc592596f62)
If your D drive is anything other than type Local Disk and format NTFS, then that will make a difference to how things work.

So, currently, if you set the view you want for Downloads using WinSetView, and click Submit, you're not getting that view in your D:\Downloads folder. Is that correct?

**Comment by Raynbda** [comment]
it's a local disk NTFS. I just tested changing the folder template to music and it worked. I think i now remember that i might have created another folder under d drive, called it downloads and gave it the icon because i had issues with moving it from c drive. I tried looking for the real downloads folder right now and i found 3 under "C:\Users\Public\Downloads" "C:\Users\Default\Downloads" "C:\Users\Administrator\Downloads" but they all act the same as the one in d drive. I can change folder template and when i submit changes in winsetview they don't apply. Is there a way to associate the folder in d drive with the downloads folder template using registry maybe?

**Comment by Raynbda** [comment]
I have created a folder under C:\Users\(myUsername)\ called Downloads and the settings i set in winsetview now apply. When go into properties and try to move the folder to d drive i get an error: The folder can't be moved here 
![explorer_TUApXCX3ws](https://github.com/user-attachments/assets/fdd4d29d-ea39-48e7-b181-361c65ba5086)
Dragging the folder from c to d drive makes the folder like any other folder. And i don't want to keep the downloads folder in c drive because it will make moving files to my d drive (where i store almost all my files) slow

**Comment by Raynbda** [comment]
Ok finally fixed. I've used this article "https://www.winhelponline.com/blog/windows-10-shell-folders-paths-defaults-restore/ " to determine the registry key of the downloads shell folder and then changing the location in this value -> **{374DE290-123F-4565-9164-39C4925E467B}** under **HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell** Folders from **%USERPROFILE%\Downloads** to **D:\Users\Downloads**
After I restarted, the folder now acts normally and uses the template that is set in winsetview.

**Comment by LesFerch** [comment]
Sorry I couldn't get back to you sooner. Glad to hear you got it sorted, but please note that all you had to do is use the `Location` tab in the `Downloads Properties` dialog to change its location. That will set the registry entries for you, refresh Explorer, and will give you the option to move the files for you to the new location.

![image](https://github.com/user-attachments/assets/50051822-1fe8-4213-beb7-964700df3127)

**Comment by Raynbda** [comment]
The d drive version of the downloads folder was actually in d\users\downloads all along. I got the error anyway.
