### ISSUE TITLE
"Use Windows 10 Explorer on Windows 11" stopped working after recent Windows update

### ISSUE THREAD

**Issue by cetso** [LesFerch/WinSetView#130]
Here is the current view after submitting with "Use Windows 10 Explorer on Windows 11" enabled:
![image](https://github.com/user-attachments/assets/4a03a237-f4e0-4edb-a8aa-7e6770141551)

Here is my info:
Edition	Windows 11 Pro
Version	24H2
Installed on	‎10/‎1/‎2024
OS build	26100.2033
Experience	Windows Feature Experience Pack 1000.26100.23.0

**Comment by LesFerch** [comment]
Thank for reporting that. I see the same issue. I'll get it fixed ASAP.

In the meantime, you can use [SwitchExplorer](https://lesferch.github.io/SwitchExplorer/). It still works correctly.

**Comment by cetso** [comment]
Thank you.

Is there a way to make a donation?

**Comment by LesFerch** [comment]
Fixed. The problem was caused by how I was checking the build number.

Just download a fresh copy. I didn't update the WinSetView version number. I'll increment the version number next update.

Thanks for the donation offer. I'm not set up for that, but I appreciate the thought. It's just a hobby for me. 🙂
