### ISSUE TITLE
Low priority: show font names in their own font

### ISSUE THREAD

**Issue by stamminator** [LesFerch/WinSetView#135]
It would be nice to show each of the available fonts in their own typeface instead of the currently selected one so you don't have to go one-by-one to see what they look like.

<img src="https://github.com/user-attachments/assets/33093346-355c-4fc8-8fd5-dd561bd34f0f" width="569.6" />

**Comment by LesFerch** [comment]
It's possible, but there's a lot of work to do first.

Here's how it would look. Note that a lot of the fonts look the same because they are mostly san serif fonts  for different languages (usually based on Segoe).

![image](https://github.com/user-attachments/assets/4d33aa7d-1c49-413b-a697-3f0ade566feb)

The problem, currently, is that feature only works in MSHTML 11 mode. I'm currently running in 8 mode because any mode higher, using VBScript, is unstable with the amount and nature of the code involved. I have rewritten all of the code in JScript (currently available as a beta) and that appears to have fixed the stability problem so that I can now use 11 mode, but it's still set to 8 mode because I would have to completely rewrite the table code to work in 11 mode, otherwise the Columns page is all messed up like this:

![image](https://github.com/user-attachments/assets/b2980cf8-4c55-4d68-a997-92ed8ef73f47)

**Comment by LesFerch** [comment]
I spent a few frustrating hours on this and couldn't get the table contents aligned correctly in 11 mode. The static header is fine. It's just the dynamically generated content that ignores the widths. For now I'm closing this as not planned as I have other projects to work on. Sorry.

**Comment by stamminator** [comment]
@LesFerch No worries, it was a small thing anyway. Thanks for taking a look.
