### ISSUE TITLE
WinSetView Requires MSHTML 11

### ISSUE THREAD

**Issue by LesFerch** [LesFerch/WinSetView#138]
Windows 7 build throws error:

![image](https://github.com/user-attachments/assets/50cd3f99-31a1-4377-8d06-3aa40eb23472)

**Comment by LesFerch** [comment]
Your issue Is that WinSetView requires MSHTML 11 and your Windows 7 build only has MSHTML 8 (or nothing at all if you ripped that out).

The documentation has been updated with the specific [System Requirements](https://github.com/LesFerch/WinSetView/blob/main/System-Requirements.md)

**Comment by LesFerch** [comment]
Comment from user:

"Your choice of scripting language is the issue and because of this is reliant upon an antiquated browser engine that hasn't been used for it's intended purpose since 2015...

Now you mentioned a rewrite to a C# program which would solve the problem. As would a conversion to a batch script.

I also see within the folder powershell components. This could also potentially work.

Is there an update on any of this rather then creating a dependency on the cancer that is internet explorer and the deeply embedded install that takes hours to properly uninstall by hand through the registry since simply uninstalling via "add/remove programs" leaves hundreds of components behind?"

**Comment by LesFerch** [comment]
The tool works just fine on the vast majority of machines out there.

Hundreds of hours of work have gone into this tool. It's no small task to rewrite it from the ground up. GUIs are hard work. I may rewrite it in C# some day, but it will likely take me a year or more (I do have other things to do).

A batch script would not work for replacing the GUI, since batch files don't provide GUI elements.

The documentation provides information for running just the PowerShell script via the command line. You will have to hand edit the INI file or use a computer that has MSHTML 11 to edit the INI file.

If you want to use the tool with the GUI you will need to install MSHTML 11. You can uninstall IE and probably can even delete the entire Internet Explorer folder. That's all I can offer as a solution for now. It's a free tool. I do what I can, but I can't make everyone happy.

**Comment by Candlemass** [comment]
> The tool works just fine on the vast majority of machines out there.
> 
> Hundreds of hours of work have gone into this tool. It's no small task to rewrite it from the ground up. GUIs are hard work. I may rewrite it in C# some day, but it will likely take me a year or more (I do have other things to do).
> 
> A batch script would not work for replacing the GUI, since batch files don't provide GUI elements.
> 
> The documentation provides information for running just the PowerShell script via the command line. You will have to hand edit the INI file or use a computer that has MSHTML 11 to edit the INI file.
> 
> If you want to use the tool with the GUI you will need to install MSHTML 11. You can uninstall IE and probably can even delete the entire Internet Explorer folder. That's all I can offer as a solution for now. It's a free tool. I do what I can, but I can't make everyone happy.

@LesFerch 

Sure but I don't personally care about a UI...

A batch script is perfectly adequate for this task. You simply create a separate batch for each of the different view types. Copy + paste the bulk code and edit each to correspond with the folder view...

Anyway, I don't have an issue manually editing the Win7.ini file within the "defaults" folder.

Since I haven't dug into the registry to discern the variables, what lines do I have to edit for "medium icons" to apply system wide?

After this is done, I'm assuming the .ps1 file within the main directory of the folder will apply the changes?

Thanks.

**Comment by LesFerch** [comment]
@Candlemass

Try the new beta (**WinSetViewJScriptBeta.zip**). Download from [here](https://github.com/LesFerch/WinSetView/releases/tag/3.0.2).

I've managed to make it work with MSHTML 8. Please try it and let me know if it works on your computer.

**Note**: It will pop up a message on startup stating that MSHTML 11 is recommended. Just click OK and it should load up. This message box is actually required. There's a weird bug/restriction in MSHTML 8 that will cause an "Access is denied" error if the program code tries to change the window size and position before the user has provided any input. The reason the code changes the window size and position is to place the window as it was when you last closed it. Otherwise, I would have to open it to a fixed size and position which would be more annoying than clicking OK on the message box.

**Comment by Candlemass** [comment]
@LesFerch

Appreciate the update.

I think I might have some time tonight to give this a try. I will report back after doing so. Unfortunately I haven't been home to mess around with this any further since our last correspondence.

A little background is that my daily drivers are linux machines and this was simply a project box for a very specific use case. The goal is the slimest system realistically possible to create a baseline system image. This means no install of unnecessary obsolete components and meticulous maintenance to strip the registry of anything not needed outside of basic operation and the specific task. This means installing anything temporarily especially components that add hundreds of entries of clutter to the registry and simply create additional work to manually go through to restore after the fact are a no go. It also means that I will avoid the dumpster fires of windows 10/11.

Thanks for the continued effort and letting me know about the error in advance. I'm not too concerned about it as long as the final outcome is achieved.

**Comment by Candlemass** [comment]
I tried the beta supplied in your link and it works well. The themes are a nice touch to the UI.

Would it be possible to add a setting to set the default view as "align to grid" as well?

https://i.postimg.cc/k4QV0gP3/Align-To-Grid.jpg

This option doesn't appear to be currently present.


Another minor addition that might be helpful would be tool tips when hovering the mouse over the check boxes. A couple of the settings are pretty vague and took some trial and error to figure out what they did. Thankfully you have added a revert feature utilizing registry backups so it's doable without consequence.

Thanks again for the beta update as it currently stands.

**Comment by LesFerch** [comment]
The "Auto arrange" and "Align to grid" options are applied per folder, so it's not a simple global setting like "Disable full row select". Those options are also only available when using "Legacy row and spacing" (aka Windows XP/Vista view mode) and are therefore not part of the FolderTypes registry key defaults. I'm currently taking a look to see if there is any practical way to set defaults for those options.

In regards to in-app help, anything like that has to be translated into 32 languages, so it's always a big job to add any new text to the interface. So, I prefer to keep explanations as much as possible in the manual. The manual is only provided in English, but users can right-click to tell the browser to translate the text into another language.

All options are documented in the manual, so my question is: were some options inadequately described in the manual? If so, I can work on improving those items. The Help button is context sensitive to the section. That is, if you click Help while in the "Folder View Options" page, you will be taken directly to that part of the manual. Of course, if your target machine doesn't have Internet access you'll have to refer to the documentation on another computer (or your phone).

What I can probably do is make the help more context sensitive. That is, something like a `?` icon beside each option (or Alt-click or Ctrl-click the item) that takes you directly to that option in the manual.

**Comment by Candlemass** [comment]
@LesFerch 

Yes, these additional view options were enabled because otherwise the microsoft default is too rigid with the inability to move files within a folder, a forceful alphabetical sort with folders first and depending on the type of files within a folder this is not always adequate. Editing file names of files also doesn't take effect until you exit and reopen a folder with the default settings which is highly annoying.

Your last suggestion regarding links to pieces of the manual I believe to be the best option. In my example the machine winsetview is currently being applied on is not connected to the internet at this time so linking to online documentation doesn't work.

I will wait to hear back regarding any progress. Cheers.

**Comment by LesFerch** [comment]
I've added options for "Auto arrange" and "Align to grid" and also an option to set the system text color.

![image](https://github.com/user-attachments/assets/4565aba7-95a7-41bf-a3ec-a31061cbc2ee)

See the [manual ](https://lesferch.github.io/WinSetView/doc/v3/Manual.html#folder-view-options-1)for details.

I did not add any further context sensitive help in the app. It requires too much time and effort.

**Comment by Candlemass** [comment]
@LesFerch

Perfect. That's all I'm really looking for personslly since I now know what everything does.

The additional context was only a minor suggestion for new users. If you prioritize that all the text be translated to several dozen languages, I understand that it's a lot of work to complete. I just figured since the English manual was already complete that it wouldn't hurt.

Thanks sgain.

**Comment by Candlemass** [comment]
@LesFerch

I tried the updated build. All seems to wotk well except "align to grid" and "auto arrange" view settings are not available in the "C:/" folder.

I previously created a registry edit that accomplishes this system wide including the "C:/" folder but it conflicts with winsetview if run afterwards.

Would you like me to upload it so that you can use t as a reference to incorporate into winsetview so that all folders are consistent?

**Comment by LesFerch** [comment]
I have "align to grid" and "auto arrange" on C:\ on my test Windows 7 build.

**Comment by LesFerch** [comment]
I see that issue on my Windows 10 machine. Looking into it...

**Comment by LesFerch** [comment]
Got it. It happens when "Use General Items column settings for connected devices" is checked. I just have to move the code that applies those settings after the code that sets the Vista/XP view mode.

**Comment by Candlemass** [comment]
@LesFerch

Glad you got it sorted out.

Will await the new build and confirm.

**Comment by LesFerch** [comment]
@Candlemass The new beta build is now available to [download](https://github.com/LesFerch/WinSetView/releases).

**Comment by LesFerch** [comment]
@Candlemass I was able to eliminate the dialog prompt on startup by having a small empty dialog that just flashes for 1/10 of a second. The new beta is available now to download.

**Comment by Candlemass** [comment]
@LesFerch 

Tested the new build and all conflicts appear to be fixed at least with the settings I deployed.

Error dialog also now presented with behavior as described.

Nice work and thanks for addressing this.
