### ISSUE TITLE
Additional column headings?

### ISSUE THREAD

**Issue by engelhro** [LesFerch/WinSetView#2]
Hello,

Thanks for your great tool (and the detailed explanations in the Readme, which made me understand Explorer's behavior a lot better)!

Is it possible to somehow provide additional column headings? You wrote:

> There are many more heading choices in Explorer, but these are the ones that are most likely to be applicable globally.

But I'm missing at least the "Owner" column which I have included in all my views. And others users may *also* have some more columns they regularly require. I understand that offering the full list of more than hundred columns which are available in Windows is neither feasible nor useful, but a way to add a few more than the current sixteen would be fine…

This could be accomplished in two ways:

- **Fixed/for all users**: statically adding new columns to your tool from time to time which got requested by users (like me in this case)

or

- **Flexible/for each user**: offering functionality where users themselves could enter the columns they need (e. g. via some technical ID referencing the column heading as used by Explorer)

Thanks for considering such a feature!

**Comment by brake4bots** [comment]
Thank you for the feedback and excellent suggestions. Related to this, I have another request to also allow setting global column widths. I'll try to work both into a future upgrade. It will require a significant UI redesign and probably will include a more advanced method to save user's choices, such as an INI file, XML file, or registry entries. I'll also consider a quick fix, to just add a few more column headings, depending on what other requests come in.

**Comment by brake4bots** [comment]
I'm thinking of adding four more column choices for now and then later do a
major UI redesign to accommodate user column choices. In addition to
"Owner", what other three column headings would you suggest?

**Comment by engelhro** [comment]
> […] Related to this, I have another request to also allow setting global column widths.

Ah, that would be awesome! Especially as some widths cannot be set manually in the Explorer (the input field seems to be only three digits wide, so a width of more than 1000 cannot be entered – you can only achieve such widths by dragging the column heading).

> […] probably will include a more advanced method to save user's choices, such as an INI file, XML file, or registry entries.

That would be pretty neat also. A file based storage would make the settings "portable" (so they can get backed up and re-used later).

> […] In addition to "Owner", what other three column headings would you suggest?

Right away I have no proposal, maybe others can chime in here and propose a few columns in the next days.

One information I regularly need is the link type (if an entry is not a native file or directory), i. e., what you see in a command shell in a directory listing usually as 3rd column. For example:

- `Symlink` (file)
- `SymlinkD` (directory)
- `Junction` (directory)

I'm not sure whether that classification is available as column (it probably is, but I haven't found it yet – I use a German Windows, and maybe the correct title of that column is just difficult to identify due to the translation).

If you know that column, that would useful to add as well.

Just two columns left… ☺

**Comment by brake4bots** [comment]
1000 pixels on my old 1600x900 screen would be crazy wide, but on an 8K (or even 4K) monitor it's not unreasonable. That's one reason why Explorer should be updated to prompt for the column width in ems instead of pixels. Another reason is that the column width defaults are already stored in the registry as ems. Ems are relative and are roughly equivalent to 1 character. On my little 96 dpi screen at 100%, 1 em is 8 pixels, at 125% it's 10 pixels, and so on. I mention all this because I'm implementing the column width option to work in ems (with a Help button to explain). I was thinking two characters (i.e. 99 ems) would be plenty (the Windows default for the Name column is 34 ems). I could allow up to 999 ems, but my concern is that people won't read and will enter large values thinking it's in pixels. Well, I guess I can't be blamed for that, but guidance is good. What do you think? 99 ems is more than 100 characters wide. Would you really want to go wider as a global default?

AFAIK, there's no link type column option built into Explorer. Tools already exist to provide overlay icons to indicate the link type. Take a look at: https://elsdoerfer.name/ntfslink and https://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html. There may be more out there. Hopefully one of those will work for you.

I'll add a new checkbox row with the "Owner" column and leave room for adding three more column headings as requests come in. In the future I would like to do a completely new UI design with flexible column choices, but that will take a lot of work, so hard-patching will provide a bridge for now.

**Comment by brake4bots** [comment]
A new version is now available. It adds an "Owner" column heading and column width settings for the Name column (first column) and a separate width setting for any Path type column headings. Selecting, and setting widths for, any of Explorer's column headings is on the To Do list.

**Comment by LesFerch** [comment]
WinSetView v2 now provides an interface to choose from any column headings (a list of more than 300 on Windows 10).

**Comment by engelhro** [comment]
Wow, great! Thanks a lot, much appreciated! 👏

Unfortunately after testing I discovered some grievances with the current WinSetView implementation (width of columns only in "em" and not in pixel as Explorer shows it by default, weird error messages with meaningless message boxes due to missing error description and empty header, etc.), so I'll guess I need to wait a little bit for a more advanced and bug-free / polished version…

Limited time currently on my side, sorry 😓, otherwise I'd create proper issues for my problems. Maybe I can do so in a few days.

**Comment by LesFerch** [comment]
Hi. Thanks for commenting.

Yes, Explorer shows pixels for column widths, but it only uses ems in the
registry, for good reason. Since WinSetView is essentially a FolderTypes
registry key editor, using the registry values makes sense. Also, pixels
don't make sense for the interface because pixel density can vary
dramatically. The programmers knew what they were doing by using ems, but
the designers thought pixels are more "familiar". Anyhow, ems are explained
in the readme and I'm not going to translate ems to pixels (you have to
account for pixel density and screen scaling). It's easy enough to get used
to ems and you won't have to change the values when you upgrade to a higher
pixel density screen (or I won't have to figure out in code what the new
values should be).

The messages are intentionally as brief as possible to simplify translation
to other languages. An important goal of this project is to make it
multilingual. I've provided translations for 31 languages. Any dialogs that
have help or explanations greatly increases the translation work, so the
dialogs will remain brief. I will add information to the readme file as
questions come up. Yes, the readme is in English only, but non-English
speakers can use a combination of online translation and/or asking an
English speaking friend to interpret. Not perfect, but in time, maybe
others will translate the readme file.

The only dialog I can think of that matches what you describe is this one:
[image: image.png]
In order to avoid additional stuff to translate, it's very much like an
Ikea instruction page, but the readme file does say that Explorer is
limited to 21 column headings. Most users will never try to select more
than 21 column headings and, if they do, I figured they would pretty
quickly figure out the error means they reached the limit. I'll update the
readme to show a picture of this dialog. I intend to keep it Ikea-like. ;-)

Please let me know if there was any other unclear dialog. I will fix any
bugs promptly, but I don't see any to fix yet. More specific feedback will
be very much appreciated.

Thanks,
Les

**Comment by engelhro** [comment]
> Hi. Thanks for commenting. Yes, Explorer shows pixels for column widths, but it only uses ems in the registry, for good reason.

I understand the internal format used for storing the columns widths and that it makes sense *there*. I just partially disagree with your conclusions.

> Since WinSetView is essentially a FolderTypes registry key editor, using the registry values makes sense.

Well… You consider WinSetView to be kind of a registry key editor, while me (and other users probably) consider it to be be tool that should make their life (with Windows and its explorer) easier :smiley:

And that's what it does not currently:

- I would have to find out my screen density.
- I would need to determine the current scaling factor.
- I would need to calculate.
- I would even need to find out the correct formula to apply! The readme only lists some values for the concrete screen density of 96 dpi with three different scaling factors, but does not explain the general formula I would need to use for other values of both screen density and scaling factor.

I consider that as not optimal from an end user's point of view.

> […] It's easy enough to get used to ems and you won't have to change the values when you upgrade to a higher pixel density screen (or I won't have to figure out in code what the new values should be).

I have at least two issues with that:

1. The width in ems can be specified in WinSetView only as integer, resulting in multiples of a value in pixels. At the same time, I can set the width in the explorer on a scale of pixels (and that gets remembered correctly by Windows!). So I assume the width (in ems) is stored internally as float?

	Can at least that degree of detail get exposed via WinSetView, so I can set the desired widths with the precision I want?

2. If you really insist on ems, would it be possible to read the columns and width values (for a specified folder) on startup and use those as a starting point?

	Showing a fixed list of proposed columns with a default width of 34 ems would destroy the user's view once he hits the `Submit` button, overriding his/her current settings (while the intention might have just have been to adapt the current view a little bit or even apply it to other folders from a given "master" directory).
	
	Looking at ems as unusual unit intead of seeing pixels obscures this potentially destructive behavior and makes the user less aware of the unintended effect.

> […] Unclear error message
>
> The only dialog I can think of that matches what you describe is this one:
>
> ![image](https://user-images.githubusercontent.com/79026235/124494511-eb6ad200-dd84-11eb-8198-adea1bb7e176.png)
>
> In order to avoid additional stuff to translate, it's very much like an Ikea instruction page, but the readme file does say that Explorer is limited to 21 column headings.

Yes,that is indeed the error message I meant.

The problem is: it appears even with less than 21 columns selected!

Actually, I start WinSetView, click on the `Columns` button in the "General" section, and then every click on any checkmark box triggers the message. Both lists (columns to show and columns for right click menu) are left on default, i.e., with way less than 21 entries preselected in each of them.

> Most users will never try to select more than 21 column headings and, if they do, I figured they would pretty quickly figure out the error means they reached the limit.

Well, not having reached that limit as all, the error message was quite perplexing to me, nothing to "figure out". WinSetView, out of the box, was just not working for me. So while it might be clear and "easy" for you as developer, such a message is nothing but confusing for the user.

Developer's problem (I've seen that too often): what you think users would do or figure out, is almost never what users actually do or figure out :wink:

> More specific feedback will be very much appreciated.

You're welcome. I hope I have described my view in a helpful manner.

**Comment by LesFerch** [comment]
> Well… You consider WinSetView to be kind of a registry key editor, while me (and other users probably) consider it to be be tool that should make their life (with Windows and its explorer) easier 😃

The two views are not mutually exclusive. My goal is to make the task of setting File Explorer _default_ views as easy as possible (or perhaps I should say "practical"). The default views are stored in the _FolderTypes_ registry key, so that drives some of the interface choices.

WinSetView v1 had a simpler interface, but also many limitations. I could not address all of those limitations without adding a bit of interface complexity, but I certainly did my best to keep it simple (somewhere around  two hundred hours of work actually).

In regards to the >21 columns error message...

When I posted v2, I should have included a Win10.ini file that only had the default Windows 10 columns (and right-click column choices) selected, but I actually included an INI file where I had already selected 21 column headings for the right-click menu:

![image](https://user-images.githubusercontent.com/79026235/127204758-38ec4b29-8164-4956-a649-3305c0a6e658.png)

The limit of 21 applies to the column heading right-click menu as well. So, with those selections already made, you need to uncheck one or more items from that last column before you can select a different column heading. I have since replaced the INI file in the **Main** branch on GitHub with one that has only a few pre-selected items. You can also just delete the INI file to start up with nothing more than the "Name" column selected.

I hadn't at first realized I had posted a file with 21 items pre-selected. When I saw that, I realized why you encountered the 21 limit error message right away. Apologies for that.

In regards to "ems"...

The _default_ column width for any given column in Details view is saved as an _integer_ value in _ems_.

When you set a column width by pixels in File Explorer's **More** menu, it's saved in binary format in the **Bags** registry key, along with any other view settings you may have set for that folder using File Explorer. The Bags registry key is the volatile registry storage key for folder views that overrides any of Windows default views. WinSetView sets _default_ views using the _FolderTypes_ key. It does not mess with the Bags key (which is a sequence of numbered binary entries) with the lone exception of the "This PC" and "Network" views option (which breaks easily because it's not a proper default - see readme).

So, I can't set _default_ widths with any more precision than ems allow and it's a major can of worms to have the interface in pixels. I have put a lot of thought into it. It's not nearly as simple as it looks, but I don't agree that you have to do any calculations. Just think of ems as characters, enter a number and try it out. I set my default "Name" width to 40 and my "File Extensions" column to 6. A bit of trial and error, but nothing more difficult then entering a number, clicking **Submit**, and seeing if it looks okay. Once you've got it set you're done and you won't have to rethink it when you upgrade to a higher pixel density display.

Having said that, I'll take one more look at it. Perhaps an easy update will be some way to show the estimated pixel equivalent when you right-click or hover over the value.

**Comment by LesFerch** [comment]
You can now enter the column widths in pixels. Hold the **Alt* key and click a column width input field to get a dialog to edit the value in pixels:
![image](https://user-images.githubusercontent.com/79026235/127723197-4b19497a-cf17-43e2-b7ac-df23e4b33608.png)
