### ISSUE TITLE
HTA was blocked because this type of file can harm your computer

### ISSUE THREAD

**Issue by dajhorn** [LesFerch/WinSetView#27]
Edge 99 in the current Windows 11 Pro 21H2 Build 22000.556 release won't run HTA files.  Reproduce by doing this:

1. Unpack WinSetView-main.zip

![image](https://user-images.githubusercontent.com/494022/159274841-a905804b-882a-45a6-ac8b-8058a12828d1.png)

2. Double-click the HTA file and get the security error.

![image](https://user-images.githubusercontent.com/494022/159275088-c857a5be-538c-4563-b6f9-be7ad72f5c8d.png)

3. Choose "Keep" in the downloads menu.
 
![image](https://user-images.githubusercontent.com/494022/159275262-1ef058e2-6a9e-4508-b3a4-101ddaa37edb.png)

4. Click  "Open" in the downloads menu.

![image](https://user-images.githubusercontent.com/494022/159275386-cdbd0f0f-5eb2-4282-bc64-cdb3ccbf453a.png)

5. This trips the security check again and corresponding `.crdownload` instances will stack in the downloads menu and in the downloads folder.

![image](https://user-images.githubusercontent.com/494022/159277414-a2b12983-d9e6-410b-bd38-46786c31431b.png)

6. Go back to step 2 forever.

Is there a way to disable the security check or otherwise force the Edge browser to open the HTA files on recent Windows 11 builds?

**Comment by LesFerch** [comment]
By default, Windows does not block HTAs. The block may be set as a GPO on your machine. Is that a company owned computer (i.e. is it centrally managed)?

**Comment by LesFerch** [comment]
Based on the icon, it appears that the HTA extension is associated with Edge on your computer. It must be associated with mshta.exe in order to work.

**Comment by dajhorn** [comment]
That fixed it.  "Microsoft (R) HTML Application host" was already in the "Opens with" list.

The file property box now looks like this:

![image](https://user-images.githubusercontent.com/494022/159328757-944d4ea4-91ef-4244-9151-31cd6c78fd30.png)

I installed this Windows 11 instance from a non-retail ISO today, so this computer is fresh and there are no GPOs or anything like Active Directory installed on it.

**Comment by dajhorn** [comment]
I didn't realize that this particular design mistake in Windows File Explorer could be fixed.   Thanks for doing the heavy lifting by figuring out how to mitigate the bad default column layout.  The "File Type" column greatly annoys me, and this is a good way to hide it in Windows 11 everywhere.

**Comment by LesFerch** [comment]
Glad to hear you got it working and that you got File Explorer set up to your taste. Can you let me know the exact file name of that ISO? Maybe I can investigate further. If non-retail Windows 11 ISOs come preset with HTAs associated with Edge, that's a concern for me. At the very least, I will update the download and quick start guides with instructions for associating with mshta.exe. Thanks so much for posting an issue and following up. Much appreciated!

**Comment by dajhorn** [comment]
(I did more troubleshooting.)

This glitch is caused by associating HTA files with Notepad++ for editing.  The Windows 11 variant doesn't matter.

This also happens with other interpreted file types like CMD and BAT if an "edit" action is added Windows File Explorer by application software.  I reported this bug to Microsoft earlier, and it seems to affect HTA files too.

**Comment by LesFerch** [comment]
Can you post the steps to recreate the issue as it relates to CMD, BAT, and HTA files and Notepad++? 

I downloaded and installed Notepad++ on Windows 11 and had no issues. After installing Notepad++, I could right-click a CMD, BAT, or HTA file and select **Edit with Notepad++**. Double-clicking the CMD, BAT, or HTA still launched it correctly.

**Comment by dajhorn** [comment]
I'm doing this:

1. Install Notepad++ using Chocolatey.
2. Run As Administrator
3. Tools -> Preferences -> File Associations
4. Add all.

The bug expresses in two ways on affected machines:

* Only Notepad++ and Notepad will be in the "open with" list.  Choosing `mshta.exe` through the "other" selector will fail.

* The `CALL` built-in command in batch files will no-op if BAT and/or CMD files are associated.

**Comment by LesFerch** [comment]
Based on past experience, I wouldn't trust any app to mess with the associations for scripts. I would only associate non-script files types, such as TXT and CSV to an editor and use right-click to edit scripts. In general, I see no reason to touch the associations when you can right-click to edit and double-click to run.

It sounds like you want all editable files to load in the editor when double-clicked, but offer the correct option to run them (if it's a script) via right-click and Open with. That should be okay in _theory_, but very few people do that, so it's not surprising that it's an approach that has flaws.

In my testing (in a VM) after making all those associations to Notepad++, some file types were okay, such as VBS, which still offered Microsoft Windows Based Script Host under Open with. However, CMD had no Open with options. My test HTA did still had Open with Microsoft (R) HTML Application host, but that may be because I had previously intentionally broke and fixed that association. But even if it works for manually running a single script, it's still going to break when one script runs another, unless the run command is prefixed with the host exe for that script type.

I don't think Microsoft will agree that it's a glitch. They'll probably be of the position that Notepad++ took over the associations, so it's up to Notepad++ to provide the correct context menus. And the Notepad++ developers will say that it's just a text editor. That is, if you choose to associate scripts with an editor, you can't expect them to retain their full capability as scripts. I don't think Notepad++ should include script extensions in its File Association option or, at least, pop up a warning that this could break things.

**Comment by LesFerch** [comment]
Yes, I can replicate the first issue with both VBS and HTA extensions. The easy fix is to go back to Notepad++ in admin mode and remove VBS and HTA extensions form its associations. The interesting behavior is that if I then add HTA and VBS back to the Notepad++ association list, nothing appears to change. That is, they remain associated with mshta.exe and wscript.exe. But then I tried logging out and logging in and VBS was then associated with Notepad++ and Windows Script Host remained available under Open with. HTAs, however, remained associated with Microsoft (R) HTML Application host. I could force HTAs to be associated with Notepad++ (via Open with) and after doing that, Microsoft (R) HTML Application host remained as an Open with option.

The inconsistency reaffirms my recommendation to NOT mess with with script file associations.

I tried your test with the batch files while BAT and CMD extensions were associated with Notepad++ (double-clicking files with either extension opened them in Notepad++). But running them in CMD prompt, they consistently showed ALPHA BRAVO.
