### ISSUE TITLE
WinSetView.hta won't launch on Windows 11 22H2 Pro (x64) (10.0.22621.607)

### ISSUE THREAD

**Issue by radio222** [LesFerch/WinSetView#32]
WinSetView.hta (WinSetView 2.14 - WinSetView 2.41) won't launch on Windows 11 22H2 (x64) Pro (10.0.22621.607).
How to solve this problem?

**Comment by LesFerch** [comment]
WinSetView does launch on Windows 11 (all versions) so the issue is really that it doesn't launch on your particular Windows 11 machine.

More details are needed to troubleshoot. Are you getting anything displayed at all? Any error message? Is your computer managed (i.e. company owned)? Typically, a "won't launch" scenario is caused by a policy blocking HTA execution, an incorrect association, or over-protective anti-malware software. In all those cases, there's usually a message of some sort displayed. But it's possible to have a silent stop. For example, there could be a registry entry in HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\MSHTA.exe which redirects to a dummy exe that does nothing.

You could first try booting your computer into [Safe Mode](https://www.elevenforum.com/t/boot-to-safe-mode-in-windows-11.538/) and see if it then runs.

**Comment by radio222** [comment]
Thanks for the answer.

I answer your two questions:
When you run the WinSetView.hta file from Total Commander, the following window appears:
No access or the file "WinSetView.hta" is already in use.
"Application not found."

Regedit:
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\mshta.exe]
"MitigationOptions"=hex(b):00,01,00,00,00,00,00,00

**Comment by LesFerch** [comment]
When I saw that "MitigationOptions" entry, I thought that must be it, but I added that entry to my machine and WinSetView ran fine. Still, that entry is not normally present, so please delete the **mshta.exe** key from Image File Execution Options and see if that helps.

The _No access or the file "WinSetView.hta" is already in use "Application not found"_ sounds like an anti-malware program has quarantined the file, but if you still get that error in Safe Mode, then that doesn't appear to be the correct explanation.

What anti-virus/anti-malware software are you running?

And I'm assuming you've extracted the entire zip file and aren't trying to run WinSetView.hta directly from the zip file, but please confirm. Thanks.

**Comment by radio222** [comment]
I answer:
1) so please delete the mshta.exe key.
- Deleted and launched WinSetView.hta - did not start (same inscription). Did not help.

2) What anti-virus/anti-malware software are you running?
- Not using.

3) And I'm assuming you've extracted the entire zip file and aren't trying to run WinSetView.hta directly from the zip file, but please confirm. 
- Of course, I unpacked from the archive and only then launched WinSetView.hta.

Your program is very convenient and necessary for work (I use it successfully on another computer under Windows 10).
I would like to use it successfully in my Windows 11 22H2 Pro (x64) (10.0.22621.607).

**Comment by LesFerch** [comment]
I really want to solve this, but I need to think about the next troubleshooting steps. I wish the machine were on front of me. It's probably a registry setting. Perhaps a policy. Is this machine managed ( i.e. group policies set by IT department)? I suppose something could be corrupted... I hope you're available to follow up. This has happened a couple of other times, but the users did not stick with me, so troubleshooting stopped with no resolution.

**Comment by radio222** [comment]
> Perhaps a policy. Is this machine managed ( i.e. group policies set by IT department)?
answer:
No, not managed. I have full admin rights.

P.S.

I have read in several forums on the topic of not being able to run WinSetView.hta in the most recent build
Windows 11 22H2 Pro (x64), but WinSetView.hta runs without problems on Windows 11 21H2.

You can install the latest version of Windows 11 22H2 Pro (x64) (10.0.22621.607)
and test, run WinSetView.hta.
Then it will be clear exactly where the problem lies, personally with me or in the new assembly of Windows 11 22H2 Pro (x64) (10.0.22621.607).

**Comment by LesFerch** [comment]
I'm sure you can't run any HTA script on that machine, but to be sure, try something minimal like [this script](https://github.com/LesFerch/SampleCode/blob/main/HTA-misc/RandomNum.hta).

**Comment by radio222** [comment]
Did not start Windows 11 22H2 Pro (x64), writes, as it was in my first message.
Under Windwos 10 Pro (1806) started.

**Comment by LesFerch** [comment]
Thanks for confirming. It runs fine on Windows 11 22H2 Home, so I'll build a 22H2 Pro tonight and see what happens. What were those forums where you saw the same issue reported?

**Comment by radio222** [comment]
What were those forums where you saw the same issue reported?

Answer:
Permission denied if reading Location object property - Browsers | Microsoft Learn
https://learn.microsoft.com/en-us/troubleshoot/developer/browsers/development-website/permission-denied-for-location-object-properties

VBS/WSH/JS - [решено] не запускается .hta
http://forum.oszone.net/nextnewesttothread-316328.html

What is the future of mshta.exe since Internet Explorer is officially going away? - Microsoft Q&A
https://learn.microsoft.com/en-us/answers/questions/403154/what-is-the-future-of-mshtaexe-since-internet-expl-1.html

**Comment by radio222** [comment]
In order for the verification test to be completely the same, please download not just the PRO version,
namely an exact copy, like mine: Windows 11 22H2 Pro (x64) (10.0.22621.607)

**Comment by LesFerch** [comment]
The links you provided don't appear to have the same issue discussed.

Here are a couple of recent changes that _may_ be relevant:

https://learn.microsoft.com/en-us/mem/configmgr/mdt/known-issues
https://www.anoopcnair.com/windows-11-22h2-group-policy-settings-download

**Comment by LesFerch** [comment]
So far, I tested Windows 11 22H2 Home (x64) (10.0.22621.608) and had no problem. I was in the middle of installing Pro when Verizon FiOS service went down in my area. I'll have to wait until tomorrow to try again.

**Comment by LesFerch** [comment]
I just finished testing Windows 11 22H2 Pro (x64) (10.0.22621.608) and also had no problem.

**Comment by LesFerch** [comment]
The HTA is a combination of HTML/CSS and VBScript, so it's an interpreted language. Such scripts can be "compiled" to an Exe using VBSEdit, but it's really an Exe wrapper which self-extracts the script and then runs it. The same issue will occur with MSHTA at that point. When I get a moment, I'll send you that small test script as an Exe to confirm.

Let's check the HTA file associations on your computer. Using RegEdit, please export the following keys and email me the REG files:

HKEY_CLASSES_ROOT\.hta
HKEY_CLASSES_ROOT\htafile
HKEY_CLASSES_ROOT\SystemFileAssociations\.hta
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.hta

You can find my email address in the [WinSetView manual](https://lesferch.github.io/WinSetView/Manual.html).

**Comment by radio222** [comment]
Ok, I sent the letter.

**Comment by LesFerch** [comment]
Unfortunately, that wasn't it. I set my test machine with the same registry values as yours, but WinSetView continued to load fine.

At this point, I think you should do an [in-place repair](https://www.tenforums.com/tutorials/16397-repair-install-windows-10-place-upgrade.html). That should get it working.

**Comment by radio222** [comment]
Thanks!

**Comment by radio222** [comment]
The issue of launching WinSetView was successfully solved using the VbsEdit 9.9615 program.
Launched WinSetView 2.41 and configured folders and files.

**Comment by LesFerch** [comment]
I've tested many versions of Windows 11, including Windows 11 22H2 Pro (x64) (10.0.22621.608). The fact you have a _slightly_ older version (10.0.22621.607) does not matter. I'm sure you can find other Windows 11 computers that are the same, older, or newer build that will run HTAs from File Explorer without any issue. There is something specific to your machine causing the problem.

Let's determine if the issue is system-wide or specific to your user profile. Please login with a different local account and see if you still get the same error.

**Comment by radio222** [comment]
Doesn't start.

**Comment by LesFerch** [comment]
The issue is likely a problem in the registry (HKLM). Narrowing it down will require comparing with a working machine. Do you have access to any other computers (or VMs) running Windows 11? If not, then I think doing an [in-place repair ](https://www.elevenforum.com/t/repair-install-windows-11-with-an-in-place-upgrade.418/)  will fix it.

**Comment by radio222** [comment]
The issue is likely a problem in the registry (HKLM). Narrowing it down will require comparing with a working machine. Do you have access to any other computers (or VMs) running Windows 11? 
- Not.

**Comment by LesFerch** [comment]
If you can export your entire HKEY_LOCAL_MACHINE registry key and figure out a way to get that file to me (It's going to be hundreds of MBs) I could then analyze it and, hopefully, find the root cause. Otherwise, the [in-place repair ](https://www.elevenforum.com/t/repair-install-windows-11-with-an-in-place-upgrade.418/) should fix it, but we'll then never know the cause.

**Comment by LesFerch** [comment]
Similar error reported [here](https://www.elevenforum.com/t/this-app-cant-run-on-your-pc-error-when-trying-to-install-explorer-patcher.9582/page-2) with a completely different app. OP fixed issue by applying Microsoft update KB5018427.

**Comment by LesFerch** [comment]
That's great news! Thanks for letting me know. 🙂
