### ISSUE TITLE
it's not reading current folder settings?

### ISSUE THREAD

**Issue by Owyn** [LesFerch/WinSetView#42]
Everything seems to set to inherit and default, even thought in my windows I have all folder types already set up - .e.g extra big thumbs for Picture type folders, but the app doesn't show that - would be very nice if app read already existing settings so we could just edit em instead of setting up everything from scratch for each item

![image](https://user-images.githubusercontent.com/1309656/197880462-49d040b4-1926-462b-b533-fe4eddb62cce.png)

**Comment by LesFerch** [comment]
If it were possible to read all of your current default folder view settings, I would have done that already.

The _defaults_ that you can set for the five major folder types (using the poorly named "Apply to Folders" button) are not stored in a nice human readable format, like the FolderTypes registry key. Instead, they are saved to `HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Streams\Defaults` in an undocumented **binary** format. This format has been the same since Windows 7 and, over the years, people have reversed engineered some of it, so I can determine the major view setting (i.e. Details, List, Medium Icons, etc.) but determining things like sort keys and order, group by   choices, column heading choices and their order and width, etc. is just not possible.

So, yeah, you'll have to set your defaults again in WinSetView, but, once you've done that, you'll never have to set those defaults again. Anytime you build a new machine or add a new user, you can just run WinSetView to get all your preferred defaults set in File Explorer with one click.

**Comment by Owyn** [comment]
>  I can determine the major view setting (i.e. Details, List, Medium Icons, etc.) 

That'd be great already actually, so we'd be able to quickly understand how current things look and what can and should be adjusted and to which direction (e.g. not change something you are already content with, or just change one setting while keeping others default without the need to set them from scratch)

**Comment by LesFerch** [comment]
I spent some time looking at this request (i.e. read current folder settings). I concluded it's not worth the effort (and it's a big effort) because: 1) WinSetView is designed to show the settings that have been saved in its INI file. As a portable app, your preferred settings can be easily carried to another computer. In that scenario, it doesn't makes sense to read the current settings since they would be of little or no interest, 2) If I add a button to read the current settings, at best, it would only be the main view settings (List, Details, Icons) for General, Documents, Pictures, Music, and Videos, with lots of gaps in the information. Such a limited feature would have to come with some explanation. That would be complicated enough to communicate in English in a brief dialog, let alone 30+ other languages, and 3) I think if a user clicked a button to retrieve current settings and their main view choice was Details, they would be disappointed (and possibly open an issue) if it didn't actually show they Details column headings they currently have set as a default (which I can't easily read from that binary registry value).

So, I'm going to have to close this one as not practical to implement.
