### ISSUE TITLE
File Explorer window resetting size & position every time it's opened

### ISSUE THREAD

**Issue by JayEmmPea** [LesFerch/WinSetView#43]
Heya,

After using WinSetView to remove the annoying 'Group by' options infecting Windows 11 I no longer seem able to resize the File Explorer with any permanence. By this I mean that I open File Explorer and it opens in a fixed size in the centre of my ultrawide monitor. I resize it to something I find workable, reposition it to where I'd like it to reopen and then close it but on reopening it's reverted back to the centre with the same size it was before I resized it to how I want it. I've tried using the 'Reset Windows to Defualt view' option but this has zero effect. RF Annoying. Was working fine before using WinSetView. Any suggestions?

**Comment by LesFerch** [comment]
WinSetView clears the registry key [C]HKCU\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags[/C] so that the new defaults will take effect. That key also contains File Explorer's last screen size and position, so, on next launch, it opens to its default center location. However, that should have no effect going forward. I tested on several machines tonight (Windows 10 and Windows 11) and had no issue with it remembering its last size and position going forward.

Test conditions, of course, are not a perfect replica of your setup (e.g. I don't have an ultrawide monitor). Other variables my come into play as well. Do you have multiple monitors? Are you using a laptop or desktop PC?

**Comment by JayEmmPea** [comment]
Am using a desktop PC, with multiple monitors, 1 @ 3440x1440 + 1 @ 1920x1080. Obvs, it was only presenting on my primary display. But....

I've managed to fix this myself by using a 3rd party commerical application, something called Actual Window Manager. I wanted to test if it could be resized/repositioned and remembered. It was. Then I uninstalled and the previous 'managed' setting stayed! Now behaviour is back to normal which is amazing as I have lots of drives & partitions. Really, really happy about it. Apologies for crying wolf. I've been trying to fix it for weeks so posting here was my last resort - besides the random 'here goes nothing' attempt that bore fruit, obvs. Thanks for a great utility. 'Group by' and it's inventors need to get in the sea.
