### ISSUE TITLE
Windows 11 22H2 Home

### ISSUE THREAD

**Issue by arthniwa** [LesFerch/WinSetView#48]
Thanks for this app.

In the Windows 11 22H2 version, the explorer has a Home tab with Quick access and Favorites. After using WindSetView and only customizing the Global and Download folder type, the Home tab is no longer in the default view. I'm wondering if a new folder type can be make for the Home view so that I can keep the default look.

**Comment by LesFerch** [comment]
Windows 11 "Home" is equivalent to Windows 10 "Quick Access" even though the default grouping makes it appear like Quick Access is a subfolder of Home. They are the same folder type (i.e. same GUID).

You must _uncheck_ the box to the left of **Quick Access** (or any other folder type you want to leave at its Windows default) so that WinSetView does not create a FolderType entry for that folder type. I just tested that on Windows 11 22H2 and it worked correctly. That is, the WIndows 11 Home tab remained at the default view.

In the next release I'll make some changes so that "Quick Access" displays as "Home" on Windows 11. They also changed "Folder path" to "File location". I'll check for other renamed items and I may go with a separate INI file for Windows 11.

Please test again with "Quick Access" unchecked and let me know if that gave you the desired result. Thanks.

**Comment by arthniwa** [comment]
It works. Thank you.
