### ISSUE TITLE
Support for Windows App SDK File Explorer

### ISSUE THREAD

**Issue by mibby** [LesFerch/WinSetView#68]
Hello! Would it be possible to add support for the new Windows 11 Windows App SDK version of File Explorer? 

For the last couple of months in the insider preview dev & canary channels, Microsoft has been rolling out the new file explorer for use. WinSetView does not seem to work with it, launching with just a blank screen. I've typically used WinSetView to force a global Documents view everywhere to speed up explorer navigation so it doesn't have to gather metadata like video file time length in folders with lots of files. Since the new SDK explorer, I've not been able to use WinSetView.

**Comment by LesFerch** [comment]
Hep me here. How do I enable it? I have Windows 11 build 25346.1001 Canary and I followed the instructions [here](https://pureinfotech.com/enable-new-file-explorer-wasdk-xaml-windows-11/) to enable the new Explorer, but it didn't change. There's another, more complex, set of instructions [here](https://winaero.com/heres-how-to-enable-a-new-file-explorer-in-windows-11-build-25300/). I haven't tried those steps yet. Thought I'd ask you first.

**Comment by LesFerch** [comment]
WinSetView still works fine for me. Come to think of it, "launching with a blank screen", wouldn't be a symptom of File Explorer being different. What version of WinSetView are you running?

**Comment by LesFerch** [comment]
Although WinSetView launches and runs without error, Explorer crashes after setting my default views. Applying "Reset Views to Windows Defaults" gets Explorer stable again. Using "Win-10-Microsoft-Defaults.ini" also doesn't break Explorer, so I don't think there's some big incompatibility. It's going to take some time to isolate what's making Explorer crash.

**Comment by LesFerch** [comment]
I found the issue with that new Explorer. It crashes if "Home" is set to Group by (None). I'll have to make sure it's set to its default of Group by Group.

**Comment by LesFerch** [comment]
Now I need a way to detect if the Windows App SDK version is installed. The Explorer.exe version number doesn't help and the contents of HKLM\Software\Microsoft\Windows\CurrentVersion\Explorer is the same. Grrrr.

**Comment by LesFerch** [comment]
I'm running exactly the same Windows 11 22H2 (OS Build 25346.1001) with the App SDK Explorer. No problem here. I can't see any reason for the App SDK Explorer to cause this. If you revert back to the standard Explorer does it make any difference?

Since I'm not seeing any issue with the same build, I suggest trying a [Repair Install](https://www.elevenforum.com/t/repair-install-windows-11-with-an-in-place-upgrade.418/) and see if that gets it working properly.

**Comment by LesFerch** [comment]
Thanks for checking the FeatureManagement registry settings. I was hoping I had something that would at least work in the interim, but I guess not. Microsoft should have provided a clear way to programmatically check if the new version is enabled. Very annoying.

**Comment by LesFerch** [comment]
What's the path that you're running WinSetView from?

**Comment by LesFerch** [comment]
What method did you use to enable App SDK Explorer? I used the steps here:

https://pureinfotech.com/enable-new-file-explorer-wasdk-xaml-windows-11/

Something else to try is install another Windows build in a VM. I use [VMware Workstation Player 17](https://www.vmware.com/products/workstation-player.html) for all my VM testing.

**Comment by LesFerch** [comment]
To log what WinSetView is doing, you'd either have to modify with the HTA from 2.66 or install VbsEdit and modify the HTM files from 2.72. Much easier for me to do if I can recreate the issue.

> reinstalling programs
Which programs?

> importing all microsoft settings like privacy / group policy options
Can you send me a file or the steps you followed?

Anything I've tried to intentionally break WinSetView with the same symptoms generates an error message. Just having it stop blank (or semi-blank in the case of 2.66) is a mystery. It kind of looks like MSHTML is broken, although you wouldn't even get the partial page in 2.66 if MSHTML is removed.

**Comment by LesFerch** [comment]
I agree. Nothing there looks suspect. But something changed between the initial build and the various installs/updates that broke WinSetView. Very strange. I'm currently waiting to get the automatic update to the Windows App SDK File Explorer. Nothing yet. I couldn't find any way to accelerate that process.

**Comment by LesFerch** [comment]
Is there any chance that VBScript has been disabled on your computer?

**Comment by Meowchestra** [comment]
No worries. Maybe certain conditions get met when TPM and Pro license are used. I can only imagine some feature flag is being enabled after a restart that is breaking it. Since the App SDK explorer is still under insider builds (dev / canary) and I'm the only one that seems to experience WinSetView breaking, don't worry too much about it. It has to be some combination of vive flags. I can still set documents view with regedit batch files.

**Comment by LesFerch** [comment]
Ah yes, that would be it. ;)

**Comment by LesFerch** [comment]
Version 2.72 is now available. It now always sets the HomeFolder type to group by group, regardless of which File Explorer is enabled, so that fixes the one issue I found with the App SDK version. In hindsight, I should have always had it configured that way.

The Download Help Guide now also includes a note regarding the requirement for VBScript. In the future, if Microsoft uninstalls VBScript by default, I may rewrite it all in JScript. That's a few thousand lines of code I'd rather not touch, so we'll see about that.
