### ISSUE TITLE
setting sorting 

### ISSUE THREAD

**Issue by jodathewise1969** [LesFerch/WinSetView#7]
is it possible to set sorting ascending or descending as default?
thanks a lot

**Comment by LesFerch** [comment]
Somebody else just asked the same question. My reply was...

On my machine everything is sorted by Name ascending after running the
program. If I want to sort descending, by date, or something else, I can do
that for one folder and then apply it to all folders using the "Apply to
folders" button in Explorer. See the Readme for details about "Apply to
folder". Such changes will apply to all folders as long as you checked the
option "Make all folders generic" in my app. Otherwise, the "Apply to
folders" only applies to folders of the same type. I would have to do more
research to determine if sort order is something I can set as a default,
but even if it can be done, it would require a major redesign of the UI.
That's something I'll look at next winter.

**Comment by LesFerch** [comment]
I have added your request to the "Feature Requests" discussion topic.

**Comment by LesFerch** [comment]
WinSetView v2 lets you pick up to four sort columns and set ascending or descending order for any of them.
