### ISSUE TITLE
Desktop icons lose their position on Windows 7

### ISSUE THREAD

**Issue by Getfree** [LesFerch/WinSetView#72]
I've just used this tool and now all my icons in the desktop are arranged in some generic order, all piled up on the left side of the desktop.
This tool is supposed to change the way Windows Explorer shows folders. It should not affect the desktop in any way.

**Comment by LesFerch** [comment]
I've never seen that happen and there's been no issue opened like this before. There are some differences when you choose "Reset Views to WIndows Defaults", but even that shouldn't change the desktop icon positions. However, just to confirm, did you use that option? Also, do you happen to have a 4K monitor? There have been reports (unrelated to WinSetView) of desktop icons repositioning on 4K monitors.

**Comment by LesFerch** [comment]
I'm waiting for your reply. Also, if there were any errors displayed in the PowerShell console, please run WinSetView again, but hold the **Alt** key when you click **Submit** so that the console remains on screen.

**Comment by Getfree** [comment]
I did not use "Reset Views to Windows Defaults".
I should have mentioned that I'm on Windows 7. I don't know if that's important.

What I did was to customize the columns for the "Global" view and I disabled all other views.
I assumed that by disabling all other views, the settings for those views would either not be affected or they would be removed from the registry. Either case was fine by me as I was trying to define a single view for all folder types.

Anyways, the desktop icon positions should never be affected regardless of how the tool is used.
The following key contains the icon positions and therefore must not be touched under any circumstances.
**HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Bags\1\Desktop**

I saw in the source code that there are indeed a few code paths that end up removing that key:
https://github.com/LesFerch/WinSetView/blob/fccf61396d713585160801f2077a58a4326f5706/Tools/WinSetBak.cmd#L74
https://github.com/LesFerch/WinSetView/blob/fccf61396d713585160801f2077a58a4326f5706/Tools/WinSetBak.ps1#LL95C26-L95C26

**Comment by LesFerch** [comment]
Thank you. I see there is indeed a bug that affects Windows 7 and 8, but not Windows 10 or 11.

Prior to WinSetView 2.63, existing network folder views were not reset to match the new default views. This was due to the fact that network folder views are stored in a different registry key than other, non-network, folders. They are stored within the same key as the Desktop. So, the code in the PowerShell scripts backs up the Desktop key, deletes the parent key (so the old network folder views are cleared) and then restores the Desktop key. Windows 10 and 11 automatically create the necessary node index entry for the Desktop when Explorer is restarted and the icons remain in their original positions. Unfortunately, Windows 7 and 8 don't create the node entry, so the desktop key is then ignored and the icons revert to the default arrangement. I missed that in testing and yours is the first report of this issue since I made that change about 4 months ago.

I'm working on a fix. I'll post back when it's done.

Note: The two scripts you referenced are actually not applicable. They're separate supplemental utilities (details in the manual).

**Comment by LesFerch** [comment]
Also, please note that if "Global" is the only selected option, there won't be any changes to your default folder views. The "Global" setting is just a master setting in the WinSetView interface (i.e. no correlation to anything in Windows) that, by default, is inherited by each of the folder type entries in WinSetView. Folder views are set by type, so if all types have been unchecked, the end result is the same as just checking "Reset Views to Windows Defaults".

**Comment by LesFerch** [comment]
Bug fixed in WinSetView 2.74.
