### ISSUE TITLE
Breaks sorting somewhat cont.

### ISSUE THREAD

**Issue by Polygon1177** [LesFerch/WinSetView#76]
Under some circumstances (haven't been able to pin them down), newly created folders (after the last WinSetView Submit) might still have the Sort options in the ribbon grayed out (maybe only if created on the desktop?). If it helps: this is the case even when Use General Items view for connected devices is unchecked.

**Comment by LesFerch** [comment]
Ok. Interesting. I'll take a look at that tonight. Thanks!

**Comment by LesFerch** [comment]
I haven't been able to recreate the issue with newly created folders. It may be a Windows 11 File Explorer bug that's independent of WinSetView. If you're able to find a specific set of steps to recreate the issue, please let me know. Thanks.

**Comment by Polygon1177** [comment]
Yeah, I'm struggling to find what's causing the grayed out options. It does not happen only for Desktop folders, that much I know now. And not only for folders created after the last WinSetView submit either. Stay tuned.

**Comment by Polygon1177** [comment]
Ok, check this out.

https://github.com/LesFerch/WinSetView/assets/136083651/6a3ad52c-25b5-47fd-a135-e760bf0ddcd1

**Comment by LesFerch** [comment]
I can't recreate that behavior. I tested three ways 1) WinSetView not used at all, but default view set to large icons via "Apply to Folders", 2) WinSetView with default view set to large icons and "Use General Items view for connected devices" not checked, 3) Same as 2 except with "Use General Items view for connected devices" checked. No Sort items were ever grayed out in my tests. Weird. I didn't yet try setting my language to German, but I doubt that will make a difference.

**Comment by Polygon1177** [comment]
When I use WinSetView to go back to Windows defaults, this behavior is fixed though.

**Comment by Polygon1177** [comment]
I just switched Windows to English/US, which didn't help with this. I also switched WinSetView to English/US - again nothing.

I can't seem to uninstall this Experience Pack.

No need to upload a video for comparison - I believe you! : ) Just odd this remains broken.

**Comment by LesFerch** [comment]
Thanks for the update. There must be another variable. I'll keep testing.

**Comment by Polygon1177** [comment]
Dunno if this helps: when this happens (the Sort options in the ribbon grayed out), right-clicking inside the window allows sorting (as mentioned before), but the context menu doesn't show the currently chosen sorting option - there is no bullet point next to any of the entries.

**Comment by LesFerch** [comment]
I recreated the issue by going back to the win10.ini file that you sent me. I noticed that you had four sort levels selected and that's what makes the difference. With three or fewer sort levels selected, I don't see the issue. It's the same on Windows 10 and Windows 11. I now wonder if Explorer ever did fully support four sort levels. 🤔

**Comment by LesFerch** [comment]
It should be noted that four sort levels is probably never needed. In your case, you have Name as the first sort. Since every file in the same folder has to have a unique name, the next sort (Date modified) would only come into play in a search result (if you have the same named files in other folders in your search). So, in general, once you've picked Name as your first sort there's really no point in adding additional sorts.

An example of a common two level sort would be Type as sort 1 and Name as sort 2.

**Comment by Polygon1177** [comment]
Hey there, thanks for having continued to look into this. : ) Ok, I deactivated the forth column. The only difference now is that for sorting by size I have to do one additional mouse click, which of course is no problem.

I let you know if the grayed out sort options reappear.

**Comment by LesFerch** [comment]
Deactivating the fourth sort should make no difference to what items are displayed under "Sort" in the ribbon. Windows 11 shows the first three columns (regardless of whether they are used for sorting) and the rest are under "More". In other words, only the column order controls what three items appear under "Sort".

**Comment by LesFerch** [comment]
As I mentioned, if you selected Name for Sort 1, then Sort 2 and beyond will do nothing for you. Their purpose is to define a multi-level sort, just like you can do in Excel. You would need to select a property for Sort 1 that is not unique in order for Sort 2 to be of any use.

Example 1:

You want your Pictures folders to list files in order by file type first (BMP, JPG, PNG, etc.) and then sorted by Date modified within each file type. In that case, you would select Type (or maybe Extension) for Sort 1 and Date modified for Sort 2. Picking something for Sort 3 wouldn't make any sense unless you have a lot of files that are the exact same time stamp.

Alternatively, you could set Sort 1 to Name and set Group-by to Type to get the same ordering but with headings between each group.

Example 2:

You want your Music folders to list your MP3s first by year, then by Artist, and finally by song Title. In that case, you would select  Year for Sort 1, Contributing Artists for Sort 2, and Title for Sort 3. Of course, the files will only be properly sorted if the correct metadata (i.e. tags) exist in those music files.

Note:

File Explorer supports multi-level sorting via its GUI as well. It just doesn't provide a good interface to do it, like Excel does. To do a multi-level sort via the GUI, change the view to Details, click the column heading for the primary sort (it will display a caret or caron to indicate sort order). Don't pick Name. Pick something non-unique like Type. Then Shift-click a different column heading for the second level sort. Shift-click that column heading again to toggle between ascending and descending. You've now created a two-level sort. You can continue to add a third or even fourth level, although it's rare to have enough non-unique properties to go to four levels.

In my testing today, I was able to manually set up a four level sort, but I found that setting the sort defaults via the registry (i.e. using WinSetView) three levels is the maximum that can be preset reliably. As you saw, a fourth level causes items to be grayed out (Windows 11) or missing (Windows 10) from the ribbon's Sort menu. I also found that four levels set up as a default only sorts the initial files in the folder correctly. Adding a new file does not get sorted correctly. Whereas, there was no issue with three levels set as a default. I think I'll have to remove the fourth level from WinSetView. For now, I'll just change the PowerShell script to ignore the fourth level, since changing the GUI is a lot more work.

**Comment by LesFerch** [comment]
Sort 4 removed in version 2.76 to address this issue.

**Comment by Polygon1177** [comment]
Hey there, many thanks for your thorough explanation. I know you explained it in an earlier message as well, but it went a bit over my head. ; ) 

I actually wasn't aware Windows supports multi level sorting. Nice. But I reckon I don't need that. So yeah, I deleted all but the first sorting column.

Have a nice weekend!
