### ISSUE TITLE
Change view in specific folder

### ISSUE THREAD

**Issue by WizGery** [LesFerch/WinSetView#77]
Is there any way that I can change the view of a specific folder and its subfolders?

**Comment by LesFerch** [comment]
Short answer: No

Windows 7 and above does not provide an option to set the folder view for a folder and its subfolders (i.e. a folder tree). It only provides an option to set the folder _type_ (to one of the 5 common types) for a given folder tree.

I've looked into the possibility of adding custom folder types and, while adding a custom type is possible, _applying_ that type to a folder tree is the big challenge. AFAIK, there is no way to add to the list of folder types shown under Properties, Customize, Optimize. So, I would have to program my own Explorer extension that would allow applying a custom folder type to a given folder tree. That's something I'm looking at as a winter project, but I know it will be difficult to achieve.

Another approach, that would also require a custom Explorer extension, is to provide an option to propagate the currently set view for a folder to all of its subfolders. But this is even more complicated than propagating a custom folder type, as there is no API for setting folder views in Windows 7 and above, and, although it can be reverse engineered, it's ridiculously complicated.

In the long run, it would be best if Microsoft provided such features in File Explorer. I have been pushing hard via Feedback Hub and other avenues to get the folder type setting bugs fixed in Windows 11. If that ever gets done (fingers crossed) I will begin pushing for enhancements, such as an option to set views and/or folder type by tree, an option to disable automatic folder type discovery, and option to scan a folder tree and reset the folder types based on content (i.e. controlled folder type discovery), and so on.

I really have no more influence on Microsoft than any other user, so I encourage you to leave feedback to Microsoft via the [Feedback Hub](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332). Every little bit helps.
