### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by pwab** [LesFerch/WinSetView#86]
I just wanted to say thanks once for your [detailed](https://answers.microsoft.com/en-us/windows/forum/all/windows-11-remember-each-folders-view-settings/8f18de9d-b842-4881-9d5b-88742bc685bf) [comments](https://answers.microsoft.com/en-us/windows/forum/all/changing-folder-view-of-multiple-folders-and/bbafa799-d13e-489a-b237-e5bd80b31344) on answers.microsoft.com. Through them I quickly understood that the problem is not my incompetence, but once again a previously smoothly functioning system was broken. I won't be able to use WinSetView in my corporate environment, but it's nice to know that there are already solutions for problems that shouldn't exist.

Thanks for saving me from going insane.

**Comment by LesFerch** [comment]
You're welcome.

In regards to using it in a corporate environment, there are options. Since I worked in a corporate environment for many years, I understand the rules and restrictions. In general, there's "what will work" vs "what's allowed". Most organizations put in place restrictions (limited user rights, group policies, etc.) to bring those two concepts as close together as possible.

Some organizations are very strict and some are very loose. I wouldn't advise anyone to break their corporate rules, but it's ultimately their call.

The WinSetView package, including the documentation and additional tools, provide several options for organizations. It's targeted to IT people, who want to set Explorer defaults for each new user in an automated way, but such steps work for individuals as well.

WinSetView typically will run on a corporate machine because it does not require admin rights and only works on the user's HKCU registry settings. The interface part of the package is separate from the part that updates the registry, so that allows for avoiding using the GUI, but still being able to apply the settings. So, you can use another machine to create the INI file and just use the PowerShell script to apply the registry changes.

It's also possible to capture the HKCU registry changes on another computer and apply that to the target, but that's a lot of work to get the details right, including the correct deletions.
