### ISSUE TITLE
[SUGGESTION] Add default window sizes

### ISSUE THREAD

**Issue by LinguaOccultus** [LesFerch/WinSetView#91]
Hello!

I found this little app a very welcome solution to the extremely annoying way that Microsoft introduced years ago for the folder views and way better as settings this manually for each folder type each time – so, first of all, thanks! =) Maybe there are people out there who like this behaviour but I want my views all the same list style and that's it. ;-)

Anyway, I thought about how nice it would be to also being able to do this for windows size also in the very same easy way (if possible). When you open the Windows File Explorer, you see the default size it choses on whatever values which normally is really bad. However, when you change it, you would expect it too keep this and sometimes it does so – but mostly not!

And even when you managed a new default size which is applied to all newly opened windows, but it loses it again and again, resizes them again for an unknown reason and so forth; not to speak about updates (which mess up the current current view settings of this app also; some kind of persistence would be nice when this can be achieved).

So, I think, a default window size and maybe even position on the screen would nicely fit the topic of this app also, right?

Oh, and by the way: I guess it is a scripting limitations, but any chance to solve the path limitation issues?

Best regards,

**_Tim_**

**Comment by LesFerch** [comment]
Explorer is supposed to remember it's last size and position. I think it does for most users, so you might want to start a discussion somewhere, such as [tenforums.com](tenforums.com) or [elevenforum.com](elevenforum.com) to see if there is something specific that's breaking it for you.

Explorer does not have any option to remember the size and position for individual folders. If such a feature did exist, it would only be applicable when Explorer is set to open each folder in a new window. With tabs being the current direction, I wouldn't expect to see such an option coming from Microsoft.

I think there are a few third party apps that manage Explorer windows, but I've never used any of them, so I don't have any recommendations. Such capability is not a fit for WinSetView because WinSetView just sets Explorer-supported defaults, clears any saved views, and then exits. A program that manages Explorer window sizes and positions would be a resident (i.e. stay in memory) utility that would be adding functionality that may work well for some users, but may have undesired side-effects for others. Anyhow, that's a type of program that's beyond my skill set.

What specific "path limitation issues" are you referring to? Do you mean Explorer's inability to make a path greater then 260 characters?

**Comment by LinguaOccultus** [comment]
Thanks for the detailed explanation and no worries; I'll find another solution then and I am no developer so I only can make suggestions not exactly knowing what will work and what is possible and why.

I know there is a path lenght limitation in Windows or the File Explorer. My issue here is, that I normally store my programs for backup and availability reasons on my data drive D: and do use utilities like this directly from there. However, when I do so whit this one, I receive the error message below.

Normally it stated something about the path length and I just copied it over to my desktop and ran it from there. However, as I tried again to make the screenshot now, the error message is more detailed and explains itself now. It not seems to be the lenght but the characters used. However, strange thing is, I do use other tools this way who also used scripting over the console and the PowerShell which do work, but surely there is a reason why they do not run into this limitation.

Anyway, maybe it is helpful to know for you for some reason still, so:

![image](https://github.com/LesFerch/WinSetView/assets/90448229/c799f99c-f641-4b48-b521-ae87bea8c544)

**Comment by LesFerch** [comment]
PowerShell tripping on certain characters in folder names is something Microsoft screwed up right from the very first version and it's probably not completely fixable due to backwards compatibility issues. You would think that one of the most basic starting rules for developing a new scripting language for Windows is that all valid file and folder name characters shall have no impact on the evaluation (or parsing) of a command. Therefore, characters, such as square bracket, single quote, backtick, and dollar sign (which are all valid in Windows file and folder names) probably should not have any special meaning, but all of those do in PowerShell. Fortunately, only in very tricky situations, such as an Explorer context menu  item, do any of those special characters cause trouble, except for the square brackets. I understand that it actually may have been fixed in PowerShell Core, but I haven't tested it. I'm only interested in what works with the PowerShell version that is installed by default.

Anyhow, I spent way too much time trying to work around Microsoft's bug in regards to the square brackets and finally just put in a check that disallows those characters in WinSetView's path. And I did check with experts on this subject. See this discussion:

https://stackoverflow.com/questions/69007134/how-to-run-a-powershell-command-line-from-within-a-folder-that-has-a-name-that-c

**Comment by LinguaOccultus** [comment]
No worries, it works anyway and I know what to do. I do not use the preinstalled Powershell but the core one but since it is still an issue, it seems to be not fixed by now. However, the list of what Microsoft screwed up is very, VERY long ... ;-)

As far as I know, the Windows PowerShell will be replaced somwhen by this version in the future.

It's fine for me I just wanted to know.

**Comment by LesFerch** [comment]
My program just exits with that error if there is a square bracket in the path, regardless of the PowerShell version. It may be OK with PowerShell Core, but I would have to test that and, if it does work, not throw the error. That's something I may look at in the future.
