### ISSUE TITLE
Suggestion to add as additional function

### ISSUE THREAD

**Issue by LinguaOccultus** [LesFerch/WinSetView#98]
Hello,

just saw this news today and thought this might maybe be an interesting option. I am just testing around with the registry key and its outcome since I do sometimes have trouble with the Windows 11 File Explorer responsiveness and it also never automatically refreshed my very first tab (but does so from the 2nd and onwards); both long known issues. As I always set everything to a single view (list), which I use WinSetView for, currently, it fits my needs.

It somehow maybe interferes with the interests of this application, however. So, decide for yourself ... ;-)

[[](url)](https://www.windowslatest.com/2024/03/04/windows-11-can-open-big-folders-in-file-explorer-faster-if-you-turn-off-folder-discovery/)

Best regards,

**_Tim_**

**Comment by LesFerch** [comment]
There's no new information there and the article has the terminology a little but incorrect. It's "automatic folder _type_ discovery". See my message at the link below from April 13, 2023:

https://answers.microsoft.com/en-us/windows/forum/all/windows-11-file-explorer-is-slow-lagging-hangs/30bc56ce-9a59-42ef-8fda-3b2fee603397?page=5

Windows 11 Explorer has been aggressively applying folder type discovery ever since KB5008353 (OS Build 22000.469) which was released back in January 25, 2022. That's also when Microsoft broke "Also apply this template to all subfolders".

Automatic folder type discovery is disabled when the option to make all folders Generic (aka General items) is enabled. The article says to set the FolderType to "Not specified", but that's the same as setting it to "Generic". Anyhow, that setting has been in WinSetView all along. In the **Options** menu, check **Make all folders Generic**:

![image](https://github.com/LesFerch/WinSetView/assets/79026235/724a86c3-23f5-4f8c-9060-9758b6e54ac4)
